### ISSUE TITLE
大陆访问网页会因为头像链接导致加载转圈很长时间

### ISSUE THREAD

**Issue by Chenjiunian** [miiiku/hugo-theme-kagome#2]

**Comment by Chenjiunian** [comment]
修改成本地路径就避免了国内外的加载问题

**Comment by miiiku** [comment]
头像链接访问慢是跟你图片存放的地址有关系，可以尝试把你的头像图片存放在CDN或者其他图床上，访问会快些。

**Comment by Chenjiunian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
