### ISSUE TITLE
搜索框

### ISSUE THREAD

**Issue by ChenXuyuan97** [miiiku/hugo-theme-kagome#3]
目前没看到有搜索框，有考虑加一个吗?

**Comment by Chenjiunian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ChenXuyuan97** [comment]
抱歉，之前只在demo上看。下了代码后发现有search了

**Comment by miiiku** [comment]
后续会考虑出一个迭代更新，可以关注下，其中应该会包含搜索功能。
