### ISSUE TITLE
请修改页脚的工信部链接

### ISSUE THREAD

**Issue by Justsenger** [miiiku/hugo-theme-kagome#4]
工信部已经搬家到   https://beian.miit.gov.cn/   了哦，去年年底就被发邮件警告了X(

**Comment by Chenjiunian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by miiiku** [comment]
已修改~
