### ISSUE TITLE
文档链接失效

### ISSUE THREAD

**Issue by prj6** [miiiku/hugo-theme-kagome#6]
https://sukoshi.xyz/docs/
有一定概率打不开
readme的文档链接也全部失效

**Comment by Chenjiunian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by miiiku** [comment]
多尝试一下呢，站点有点不稳定，近期会把文档迁入到github中，或者你可以先访问[https://github.com/miiiku/hugo-theme-watermelon/tree/main/docs](https://github.com/miiiku/hugo-theme-watermelon/tree/main/docs)这里的文档查看，内容都基本差不多。
